# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: Build
      steps: 
      - script: echo "Build"
        displayName: build
      - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
        inputs:
          connectedServiceName: 'DevOps Connection'
          artifactsPayload: |
            {
              "artifacts": [
                  {
                    "name": "jeffartifactbuild",
                    "version": "1.$(Build.BuildId)",
                    "semanticVersion": "1.$(Build.BuildId).0",
                    "repositoryName": "build pipeline"
                  }
              ]
            }
- stage: Test
  jobs:
    - job: Unit_Tests
      steps: 
        - script: echo "Unit Tests"
          displayName: unit tests