# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: Build
      steps: 
      - script: echo "Build"
        displayName: build
      - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
        inputs:
          connectedServiceName: 'DevOps Connection'
          artifactsPayload: |
            {
              "artifacts": [
                  {
                    "name": "jeffartifact",
                    "version": "1.$(Build.BuildId)",
                    "semanticVersion": "1.$(Build.BuildId).0",
                    "repositoryName": "cicd pipeline"
                  }
              ]
            }
- stage: Test
  jobs:
    - job: Unit_Tests
      steps: 
        - script: echo "Unit Tests"
          displayName: unit tests
    - job: Checkmarx_Scan
      steps:
         - script: echo "Checkmarx Scan"
           displayName: Checkmarx scan

- stage: Deploy
  jobs:
    - job: UAT_Deploy
      steps: 
        - script: echo "UAT Deploy"
          displayName: uat deploy
    - job: Production_Deploy
      steps: 
         - script: echo "Production Deploy"
           displayName: Production Deploy
         - task: ServiceNow-DevOps-Agent-Package-Registration@1
           inputs:
            connectedServiceName: DevOps Connection
            packageName: jeffbigpackage
            artifactsPayload: |
              {
                  "artifacts": [
                  {
                      "name": "jeffartifact",
                      "repositoryName": "cicd pipline",
                      "version": "1.$(build.buildId)",
                      "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                      "taskExecutionNumber":"$(build.buildId)",
                      "stageName":"$(system.jobDisplayName)",
                      "branchName":"$(build.sourceBranchName)"
                  }],
                  "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                  "taskExecutionNumber":"$(build.buildId)",
                  "stageName":"$(system.jobDisplayName)",
                  "branchName":"$(build.sourceBranchName)"
              }

    

      
      
  
  

